### PR TITLE
add node gitignore

### PR DESCRIPTION
**Pull request by kMutagene**
I noticed on local testing that this repo has no gitignore, i added the [github preset for node projects](https://github.com/github/gitignore/blob/main/Node.gitignore). No more git status spam coming from node_modules ;)

### CODE REVIEW

**Comment by JonasLukasczyk** [comment]
We should add the hidden file `.DS_Store` from MacOS to the gitignore as well.

**Comment by JonasLukasczyk** [comment]
Btw, we should do this for the arc-commander as well. Running arc sync adds files like the .DS_Store.

**Comment by JonasLukasczyk** [comment]
Even then, are you saying the ARCitect should always pass the `--gitignore` flag when initializing an arc? Is there a use case where this is not desired? I would make it the other way around: always add the gitignore unless not desired

**Comment by Brilator** [comment]
>  I would make it the other way around: always add the gitignore unless not desired

Yes!

**Comment by HLWeil** [comment]
https://github.com/nfdi4plants/arcCommander/blob/59f219bc0791e3fad5563b66618d07e1b8d6066d/src/ArcCommander/defaultGitignore#L6
`DS.store` should be ignored. 
Which ArcCommander release are you using, @JonasLukasczyk?

**Comment by JonasLukasczyk** [comment]
v0.4.0 and the files are actually called `.DS_Store`

**Comment by JonasLukasczyk** [comment]
I will merge this in and add some additional ignores specific to ARCitect

**Comment by HLWeil** [comment]
> v0.4.0 and the files are actually called `.DS_Store`

Ah I see. This is fixed in the 0.5.0 prerelease.

**Pull request merged**
